 # Gopkg.toml example
 #
 # Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
 # for detailed Gopkg.toml documentation.
 #
 # required = ["github.com/user/thing/cmd/thing"]
 # ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
 #
 # [[constraint]]
 #   name = "github.com/user/project"
 #   version = "1.0.0"
 #
 # [[constraint]]
 #   name = "github.com/user/project2"
 #   branch = "dev"
 #   source = "github.com/myfork/project2"
 #
 # [[override]]
 #   name = "github.com/x/y"
 #   version = "2.4.0"
 #
 # [prune]
 #   non-go = false
 #   go-tests = true
 #   unused-packages = true

[[constraint]]
  name = "github.com/gonum/plot"
  revision = "5d72a5b2b142ffcf1ea8775811535daebc795ca9"

[[constraint]]
  name = "github.com/gonum/matrix"
  revision = "7a12dc272d1b0e2523979f093da43cb10ac150d3"

[[constraint]]
  name = "github.com/gonum/stat"
  revision = "46f36fbc74767ea5c73a5519e4fc704193a54c15"
